"""
==============================================================================
AI Dispatcher
==============================================================================

Author      : Shivam Sahu
Project     : AI-Driven Stock Market Intelligence Platform

Description
-----------
Dispatcher responsible for executing the ExecutionPlan generated by the
Planner.

Responsibilities
----------------
1. Read ExecutionPlan
2. Select the appropriate AI Agent
3. Execute the selected Agent
4. Return the final AI response

The Dispatcher NEVER:
---------------------
- Performs query analysis
- Accesses the database
- Calls Gemini directly
- Uses Qdrant
- Executes LangGraph directly

It simply delegates execution to specialized AI Agents.

==============================================================================

"""

from ai.agents.stock_agent import StockAgent
from ai.agents.news_agent import NewsAgent
from ai.agents.market_agent import MarketAgent
from ai.agents.portfolio_agent import PortfolioAgent

from ai.agents.supervisor.execution_plan import ExecutionPlan

from ai.common.logger import get_logger
from ai.common.exceptions import AgentError


logger = get_logger(__name__)


class Dispatcher:
    """
    Executes the ExecutionPlan created by the Planner.
    """

    def __init__(self):

        logger.info("Initializing Dispatcher...")

        self.stock_agent = StockAgent()

        self.news_agent = NewsAgent()

        self.market_agent = MarketAgent()

        self.portfolio_agent = PortfolioAgent()

        logger.info("Dispatcher initialized successfully.")

    # ==================================================================
    # Execute
    # ==================================================================

    def execute(self, execution_plan: ExecutionPlan) -> str:
        """
        Execute the selected workflow.

        Parameters
        ----------
        execution_plan : ExecutionPlan

        Returns
        -------
        str
            Final AI generated response.
        """

        workflow = execution_plan.workflow

        question = execution_plan.question

        logger.info(
            "Dispatcher executing workflow: %s",
            workflow
        )

        try:

            # ----------------------------------------------------------
            # Company Workflow
            # ----------------------------------------------------------

            if workflow == "company_workflow":

                logger.info("Routing request to StockAgent.")

                return self.stock_agent.run(question)

            # ----------------------------------------------------------
            # News Workflow
            # ----------------------------------------------------------

            elif workflow == "news_workflow":

                logger.info("Routing request to NewsAgent.")

                return self.news_agent.run(question)

            # ----------------------------------------------------------
            # Market Workflow
            # ----------------------------------------------------------

            elif workflow == "market_workflow":

                logger.info("Routing request to MarketAgent.")

                return self.market_agent.run(question)

            # ----------------------------------------------------------
            # Portfolio Workflow
            # ----------------------------------------------------------

            elif workflow == "portfolio_workflow":

                logger.info("Routing request to PortfolioAgent.")

                return self.portfolio_agent.run(question)

            # ----------------------------------------------------------
            # Unsupported Workflow
            # ----------------------------------------------------------

            raise AgentError(
                f"Unsupported workflow: {workflow}"
            )

        except Exception as e:

            logger.exception("Dispatcher execution failed.")

            raise AgentError(
                f"Dispatcher Error: {str(e)}"
            ) from e