"""
==============================================================================
Research Report JSON Validator

Author      : Shivam Sahu
Project     : AI-Driven Stock Market Intelligence Platform

Description
-----------
Validates and parses the JSON response generated by Gemini.

Responsibilities
----------------
1. Clean AI response
2. Validate JSON
3. Convert JSON to Python dictionary
4. Handle malformed responses
5. Return validated report data
==============================================================================
"""

import json
import re

from ai.common.logger import get_logger

logger = get_logger(__name__)


class JSONValidator:
    """
    Validates Gemini JSON output.
    """

    ########################################################################

    def validate(
        self,
        ai_response: str,
    ) -> dict:

        logger.info("Validating AI JSON response...")

        cleaned = self._clean_response(ai_response)

        try:

            data = json.loads(cleaned)

            logger.info("JSON validated successfully.")

            return data

        except json.JSONDecodeError as e:

            logger.exception("Invalid JSON returned by Gemini.")

            raise ValueError(
                f"Invalid JSON response.\n\n{e}\n\nResponse:\n{cleaned}"
            )

    ########################################################################

    def _clean_response(
        self,
        text: str,
    ) -> str:
        """
        Remove markdown wrappers if Gemini accidentally returns them.
        """

        text = text.strip()

        text = re.sub(
            r"^```json",
            "",
            text,
            flags=re.IGNORECASE,
        )

        text = re.sub(
            r"^```",
            "",
            text,
            flags=re.IGNORECASE,
        )

        text = re.sub(
            r"```$",
            "",
            text,
            flags=re.IGNORECASE,
        )

        return text.strip()