"""
==============================================================================
Company Matcher
==============================================================================

Project : AI-Driven Stock Market Intelligence System

Description
-----------
Matches companies mentioned in news articles using precompiled aliases
generated by AliasGenerator.

Responsibilities
----------------
1. Normalize article text
2. Match compiled regex patterns
3. Return matched stock symbols

==============================================================================
"""

import re
from typing import Dict, List

from ai.common.logger import get_logger
from news_mapping.alias_generator import AliasGenerator

logger = get_logger(__name__)


class CompanyMatcher:
    """
    Matches companies in news articles.
    """

    def __init__(self, companies: List[Dict]):

        generator = AliasGenerator(companies)

        self.company_patterns = generator.build()

        logger.info(
            "CompanyMatcher initialized with %d companies.",
            len(self.company_patterns)
        )

    # ------------------------------------------------------------------

    @staticmethod
    def normalize_text(text: str) -> str:
        """
        Normalize article text before matching.
        """

        if not text:
            return ""

        text = text.lower()

        text = re.sub(r"[^a-z0-9& ]", " ", text)

        text = re.sub(r"\s+", " ", text)

        return text.strip()

    # ------------------------------------------------------------------

    def match(self, title: str, article_text: str) -> List[str]:
        """
        Match companies inside a news article.

        Parameters
        ----------
        title : str
        article_text : str

        Returns
        -------
        List[str]
            Matched stock symbols.
        """

        text = self.normalize_text(f"{title} {article_text}")

        matched = set()

        for company in self.company_patterns:

            for pattern in company["patterns"]:

                if pattern.search(text):

                    matched.add(company["symbol"])

                    break

        return sorted(matched)